// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function ConvertFiles(arg1:Array<string>,arg2:main.ConversionSettings):Promise<void>;

export function GetMP4Files(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;
