// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ConvertFiles(arg1, arg2) {
  return window['go']['main']['App']['ConvertFiles'](arg1, arg2);
}

export function GetMP4Files(arg1) {
  return window['go']['main']['App']['GetMP4Files'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
